plugins_path: exp-plugins
plugins_work_dir: exp-workdir
plugins_spring_url_replace_enable: true
exp_object_field_config_json: '[
{
	"className": "cn.think.in.java.open.exp.adapter.springboot27.ResModel",
	"fieldModelsDesc": [{
		"fieldType": "java.lang.String",
		"fieldName": "email"
	}]
}
]'
exp:
  document:
    doc:
      scan:
        path: cn.think.in.java.open.exp.adapter.springboot27.example

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver